### ISSUE TITLE
please add support for Advanced_Gear from Shard :ilu:

### ISSUE THREAD

**Issue by rubenpd** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#6]
that mod is so cool i already made a nanotech vehicle but the looks_like effect breaks map memory feature showing infrared presence tile everywhere 
https://cdn.discordapp.com/attachments/252368751016542218/514132880096624641/unknown.png
any attention will be much appreciated!

**Comment by SomeDeadGuy** [comment]
in due time
there are a lot of untiled content out there still
I will close this when Advanced_Gear is added. Stay tuned.

**Comment by rubenpd** [comment]
thanks for your effort! dont rush it! take your time

**Comment by BBlankie** [comment]
![image](https://user-images.githubusercontent.com/44106380/48963898-2a82f500-efd8-11e8-81f8-2410cfcbc616.png)
nanosuit looks ugly, the rest is a fine addition, thanks

**Comment by SomeDeadGuy** [comment]
Make your own nanosuit then, smart ass! :D

**Comment by Lorith** [comment]
I guess I probably should have put better descriptions on things, so I will put in notes into the mod itself rather than keeping them in my head.  And since I'm not doing an update yet, I'll add the current notes I wrote up here.  Sorry to bug you with this since you've already started. >.<
[nanotech look notes.txt](https://github.com/SomeDeadGuy/Cata-MSX-DeadPeopleTileset/files/2612319/nanotech.look.notes.txt)

**Comment by Lorith** [comment]
Glad it helps, sorry I didn't have it before you started.

**Comment by SomeDeadGuy** [comment]
23e22e3f0ed189ca1a80b88593b08a662f60ee36
